In [2]:
import pandas as pd
csv_path = 'newboth.csv'
df = pd.read_csv(csv_path)
df

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,29,F,f,f,f,f,f,f,f,t,...,f,f,f,f,0.3,NaN,NaN,NaN,NaN,negative
1,29,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1.6,1.9,128,NaN,NaN,negative
2,41,F,f,f,f,f,f,f,f,f,...,f,f,f,f,NaN,NaN,NaN,NaN,NaN,negative
3,36,F,f,f,f,f,f,f,f,f,...,f,f,f,f,NaN,NaN,NaN,NaN,NaN,negative
4,60,F,f,f,f,f,f,f,f,f,...,f,f,f,f,NaN,NaN,NaN,NaN,NaN,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10716,30,F,f,f,f,f,f,f,f,f,...,f,t,f,f,?,?,?,?,?,negative
10717,68,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1,2.1,124,1.08,114,negative
10718,74,F,f,f,f,f,f,f,f,f,...,f,f,f,f,5.1,1.8,112,1.07,105,negative
10719,72,M,f,f,f,f,f,f,f,f,...,f,f,f,f,0.7,2,82,0.94,87,negative
10720,64,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1,2.2,99,1.07,92,negative

In [3]:
df.fillna('?', inplace=True)
df

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,29,F,f,f,f,f,f,f,f,t,...,f,f,f,f,0.3,?,?,?,?,negative
1,29,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1.6,1.9,128,?,?,negative
2,41,F,f,f,f,f,f,f,f,f,...,f,f,f,f,?,?,?,?,?,negative
3,36,F,f,f,f,f,f,f,f,f,...,f,f,f,f,?,?,?,?,?,negative
4,60,F,f,f,f,f,f,f,f,f,...,f,f,f,f,?,?,?,?,?,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10716,30,F,f,f,f,f,f,f,f,f,...,f,t,f,f,?,?,?,?,?,negative
10717,68,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1,2.1,124,1.08,114,negative
10718,74,F,f,f,f,f,f,f,f,f,...,f,f,f,f,5.1,1.8,112,1.07,105,negative
10719,72,M,f,f,f,f,f,f,f,f,...,f,f,f,f,0.7,2,82,0.94,87,negative
10720,64,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1,2.2,99,1.07,92,negative

In [1]:
from sklearn.preprocessing import LabelEncoder
# Create a LabelEncoder object
label_encoder = LabelEncoder()

df['target'] = label_encoder.fit_transform(df['target'])
# df['sex'] = label_encoder.fit_transform(df['sex'])
df['on_thyroxine'] = label_encoder.fit_transform(df['on_thyroxine'])
df['query_on_thyroxine'] = label_encoder.fit_transform(df['query_on_thyroxine'])
df['on_antithyroid_meds'] = label_encoder.fit_transform(df['on_antithyroid_meds'])
df['sick'] = label_encoder.fit_transform(df['sick'])
df['pregnant'] = label_encoder.fit_transform(df['pregnant'])
df['thyroid_surgery'] = label_encoder.fit_transform(df['thyroid_surgery'])
df['I131_treatment'] = label_encoder.fit_transform(df['I131_treatment'])
df['query_hypothyroid'] = label_encoder.fit_transform(df['query_hypothyroid'])


df['lithium'] = label_encoder.fit_transform(df['lithium'])
df['goitre'] = label_encoder.fit_transform(df['goitre'])
df['tumor'] = label_encoder.fit_transform(df['tumor'])
df['hypopituitary'] = label_encoder.fit_transform(df['hypopituitary'])
df['psych'] = label_encoder.fit_transform(df['psych'])
df['query_hyperthyroid'] = label_encoder.fit_transform(df['query_hyperthyroid'])

df

NameError: name 'df' is not defined

In [5]:
df.replace('F', '1', inplace=True)
df.replace('M', '2', inplace=True)
# df.replace('?', '2', inplace=True)
df['sex'] = df['sex'].str.replace('?', '2')
df

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,29,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0.3,?,?,?,?,2
1,29,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1.6,1.9,128,?,?,2
2,41,1,0,0,0,0,0,0,0,0,...,0,0,0,0,?,?,?,?,?,2
3,36,1,0,0,0,0,0,0,0,0,...,0,0,0,0,?,?,?,?,?,2
4,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,?,?,?,?,?,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10716,30,1,0,0,0,0,0,0,0,0,...,0,1,0,0,?,?,?,?,?,2
10717,68,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,2.1,124,1.08,114,2
10718,74,1,0,0,0,0,0,0,0,0,...,0,0,0,0,5.1,1.8,112,1.07,105,2
10719,72,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0.7,2,82,0.94,87,2
10720,64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,2.2,99,1.07,92,2

In [6]:


# Columns to impute
columns_to_impute = ['T3', 'TSH', 'TT4', 'T4U', 'FTI', 'age']

# Replace '?' with NaN and convert columns to numeric
df[columns_to_impute] = df[columns_to_impute].replace('?', '0') #.apply(pd.to_numeric, errors='coerce')

In [7]:
y = df['target']

x = df.drop('target',axis=1)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=100)

In [8]:
import joblib #trained model storage
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Create a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42) #randomseed(to generte the same test set)  100 descision trees

# Train the model on the training set
rf_classifier.fit(x_train, y_train)

# Make predictions on the testing set
y_pred = rf_classifier.predict(x_test)

# Save the trained model to a .pkl file using joblib
joblib.dump(rf_classifier, 'hyper_hypo_model.pkl')

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Accuracy: 0.9804
Precision: 0.9789
Recall: 0.9804
F1 Score: 0.9796

Confusion Matrix:
[[  38    0    0    0]
 [   0   13   23    0]
 [   1   17 2022    1]
 [   0    0    0   30]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.99        38
           1       0.43      0.36      0.39        36
           2       0.99      0.99      0.99      2041
           3       0.97      1.00      0.98        30

    accuracy                           0.98      2145
   macro avg       0.84      0.84      0.84      2145
weighted avg       0.98      0.98      0.98      2145